### ISSUE TITLE
How do i limit the number of upload files in multiple mode?

### ISSUE THREAD

**Issue by pravinfullstack** [TerryZ/v-uploader#2]
Thank you for this beautiful component, it works !
I am stuck with a situation where i want to limit my user to be able to upload only 5 images.
How do i do that? @TerryZ 
TIA

**Comment by pravinfullstack** [comment]
@TerryZ Kindly update the docs with 
"**itemLimit**" 

thank you :)

**Comment by TerryZ** [comment]
Updated on Home Page.
