### ISSUE TITLE
upload is not working 

### ISSUE THREAD

**Issue by biloo-dev** [TerryZ/v-uploader#6]
### **how i can resive the data from response controller** 

this is my code : 
`<v-uploader @done="uploadDone"
                                :preview-width="400"
                                upload-file-url="api/images"
                                delete-file-urll="api/images"
                                language='en'
                                :preview-height="300"
                                preview-img="/img/avatar.png">
                    </v-uploader>`
` <script> 
     export default {
      methods: {
             uploadDone(files){
                    if(files && Array.isArray(files) && files.length){
                        console.log(files);
                    }
                },
                }  
}
</script>`

### **code in My Controller :** 
 
![fff](https://user-images.githubusercontent.com/37638323/50874468-5d384f80-13c4-11e9-8876-933fa0dcd3e4.png)

the response ; 
![responce](https://user-images.githubusercontent.com/37638323/50874520-8eb11b00-13c4-11e9-8d59-896f45bef35f.jpg)

the Console : 
![dddddd](https://user-images.githubusercontent.com/37638323/50874565-cc15a880-13c4-11e9-9f66-7ca35df71a88.png)

i want to get responseText and Pass it to preview-img put i can't please help me Thanks

**Comment by TerryZ** [comment]
required to response the image full path in server side, and the full data format like as follow:
```js
{
    "success": true,//required field
    "error": null,  //when file upload fail, this field will set the fail reason
    "url": "https://xx/someimg.jpg"//a full path of image to show in thumbnail
}
```
